### ISSUE TITLE
Visualize users read ony nodes?

### ISSUE THREAD

**Issue by pwFoo** [Dletta/visualGraph#1]
Hi,
is it possible to start with a users  graph (users graph -> node "users") like 
```
gun.get("~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFlMAzio.y0jnHr1fYxL7vs5odgQFL-y-j_ORAs3GMgOP60C8UNg/users)
```
Got an error instead of the referenced items. 
```
sea.js:451 DOMException: The JWK member "y" could not be base64url decoded or contained padding
sea.js:1262 NO! Unverified data. {~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFlMAzio.y0jnHr1fYxL7vs5odgQFL-y-j_ORAs3GMgOP60C8UNg/users: {…}}~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFlMAzio.y0jnHr1fYxL7vs5odgQFL-y-j_ORAs3GMgOP60C8UNg/users: {_: {…}, ~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFlMAzio.y0jnHr1fYxL7vs5odgQFL-y-j_ORAs3GMgOP60C8UNg/l0nszwo6u9Luedw5FBCy: '{":":{"#":"~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFl…gzfExHraxbdYWcyxGU3sVHxRCHkiE3ewZbMtAgFmvzG5w=="}', ~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFlMAzio.y0jnHr1fYxL7vs5odgQFL-y-j_ORAs3GMgOP60C8UNg/l0nt00m6P6UUqUh24IP3: '{":":{"#":"~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFl…0Cb5D5ukfLbSt0cwLTpzOxCwOvtcmmMDGGOq6tlbqobCQ=="}'}[[Prototype]]: Object
sea.js:451 DOMException: The JWK member "y" could not be base64url decoded or contained padding
```

Works fine with console logged in `user.get('users')` and logged out with `gun.get("~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFlMAzio.y0jnHr1fYxL7vs5odgQFL-y-j_ORAs3GMgOP60C8UNg/users)` (is the correct soul).

**Comment by Dletta** [comment]
I haven't updated this to the latest version of gun. So it is possible that there was changes in sea.
If you log in in console and specify the root node to be "~VkRJzZrfvIaA4ru9Kmb1s5ypX-F8eyLJqyEnFlMAzio.y0jnHr1fYxL7vs5odgQFL-y-j_ORAs3GMgOP60C8UNg/users", will it gather the data?
Partially it also depends on the graph structure and the relay node to work properly.

Can you give me the steps you take to recreate the issue?

**Comment by Dletta** [comment]
It appears to work for me.
Logged in and logged out I can use the soul and retrieve the data, plus any child nodes.

**Comment by pwFoo** [comment]
Hi,

I need to test it. Thanks!
